---
title: "Simulations Part I - mixing vs cleaning"
output: html_notebook
---

Different simulations:

```{r}
install.packages("ggplot2")
library("ggplot2")

```


Fixed Parameters:
```{r}
#parameters:
# Recovery rate parameter
r <- 0.8
# Environment infection parameter
#alpha <- ((r*gamma)/(N+1))
alpha <- 0.002 
# Number of iterations
Iterations <- 20
#size of population
N <- 300
#number of locations
Place <- 3
#contamination levels
contamVec<- c(0.5,1,0.5)
#shedding set to 0.1
beta <- c(0.1,0.1,0.1)


###flexible parameters:

#fix to a medium "mixing level" --- how many compartments/how ridgid are the compartments?
probVec <- c(0.3,0.4,0.5)
# Environment virus decay -- how much effort is put into cleaning/new material
gamma <- 0.1

```


Condition 1: all people distributed over 3 places with no overlap:

```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.1,0.2,0.2)
# Environment virus decay -- how much effort is put into cleaning/new material
gamma <- 0.9

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC1_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1_1 [[1]],simulationOutputC1_1 [[2]],simulationOutputC1_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

ggsave("lowMixGamma09.png")

```



```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.8,0.9,0.9)
# Environment virus decay -- how much effort is put into cleaning/new material
gamma <- 0.9

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC1_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1_1 [[1]],simulationOutputC1_1 [[2]],simulationOutputC1_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

ggsave("highMixGamma09.png")
```


```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.8,0.9,0.9)
# Environment virus decay -- how much effort is put into cleaning/new material
gamma <- 0.2

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC1_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1_1 [[1]],simulationOutputC1_1 [[2]],simulationOutputC1_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

ggsave("highMixGamma02.png")
```


```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.1,0.2,0.2)
# Environment virus decay -- how much effort is put into cleaning/new material
gamma <- 0.2

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC1_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1_1 [[1]],simulationOutputC1_1 [[2]],simulationOutputC1_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

ggsave("lowMixGamma02.png")
```





```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.8,0.9,0.7)
# Environment virus decay -- how much effort is put into cleaning/new material
gammaS <- seq(0,1, by=0.1)

FinalA <- createFinalAMat (N,Place,probVec)
simulationMxTotal<- numeric() #initialize
simulationTotal <- list() #init

for (i in 1:length(gammaS)){
  simulationTotal [[i]] <- updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta) [[2]]
  simulationMxTotal[i] <- max(updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta) [[2]],
                              na.rm = TRUE)
}

data<- data.frame(Gamma = gammaS, 
                  Vals = simulationMxTotal )

ggplot(data=data, aes(x=Gamma, y=Vals)) +
  geom_line()+
  geom_point()


data <- data.frame ( Iterations = rep(seq(1,Iterations), length(gammaS)),
                     Vals = as.vector(sapply(simulationTotal, function (x) x )),
                     Type = as.factor (rep(gammaS, each = Iterations)) )

ggplot(data=data, aes(x=Iterations, y=Vals, group = Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

```


```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.2,0.2,0.1)
# Environment virus decay -- how much effort is put into cleaning/new material
gammaS <- seq(0,1, by=0.1)

FinalA <- createFinalAMat (N,Place,probVec)
simulationMxTotal<- numeric() #initialize

for (i in 1:length(gammaS)){
  simulationMxTotal[i] <- max(updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta) [[2]],
                              na.rm = TRUE)
}

data<- data.frame(Gamma = gammaS, 
                  Vals = simulationMxTotal )

ggplot(data=data, aes(x=Gamma, y=Vals)) +
  geom_line()+
  geom_point()

```



```{r}
# how many compartments/how ridgid are the compartments?
set.seed(12345)
probVec <- c(0.4,0.3,0.2)
# Environment virus decay -- how much effort is put into cleaning/new material
gammaS <- seq(0,1, by=0.1)

FinalA <- createFinalAMat (N,Place,probVec)
simulationMxTotal<- numeric() #initialize
simulationOutput<- list()

for (i in 1:length(gammaS)){
  simulationOutput [[i]] <- updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta)
  simulationMxTotal[i] <- max(simulationOutput[[i]] [[2]], na.rm = TRUE)
}

data<- data.frame(Iterations = rep(seq(1:Iterations),length(gammaS)), 
                  Vals = as.vector(sapply(simulationOutput, function (x) x[[2]] )),
                  Type = as.factor(rep(gammaS, each = Iterations) ))

ggplot(data=data, aes(x=Iterations, y=Vals, group = Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()


data<- data.frame(Gamma = gammaS, 
                  Vals = simulationMxTotal )

ggplot(data=data, aes(x=Gamma, y=Vals)) +
  geom_line()+
  geom_point()

```


```{r}
# how many compartments/how ridgid are the compartments?
set.seed(1)
probVec <- c(0.4,0.5,0.6)
# Environment virus decay -- how much effort is put into cleaning/new material
gammaS <- seq(0,1, by=0.1)

FinalA <- createFinalAMat (N,Place,probVec)
simulationMxTotal<- numeric() #initialize

for (i in 1:length(gammaS)){
  simulationMxTotal[i] <- max(updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta) [[2]],
                              na.rm = TRUE)
}

data<- data.frame(Gamma = gammaS, 
                  Vals = simulationMxTotal )

ggplot(data=data, aes(x=Gamma, y=Vals)) +
  geom_line()+
  geom_point()

```


```{r}
# how many compartments/how ridgid are the compartments?
set.seed(12345) #set seed

no.difference<- numeric()

for (k in 1:10000) {
  
  probVec <- c(0.4,0.5,0.6) #set this vector as interesting boundary 
  # Environment virus decay -- how much effort is put into cleaning/new material
  gammaS <- seq(0,1, by=0.1)
  FinalA <- createFinalAMat (N,Place,probVec)
  simulationMxTotal<- numeric() #initialize

  for (i in 1:length(gammaS)){
    simulationMxTotal[i] <- max(updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta) [[2]],
                              na.rm = TRUE)
  }
  
  no.difference [k] <- all(diff(simulationMxTotal) ==0)
}

mean(no.difference) # 0.3353 -> 1/3 no gamma doesnt make difference anymore !those difference can be very, very tiny!

```




```{r}
# how many compartments/how ridgid are the compartments?
set.seed(12345) #set seed

no.difference<- numeric()

for (k in 1:100) {
  
  probVec <- c(0.5,0.5,0.6) #set this vector as interesting boundary 
  # Environment virus decay -- how much effort is put into cleaning/new material
  gammaS <- seq(0,1, by=0.1)
  FinalA <- createFinalAMat (N,Place,probVec)
  simulationMxTotal<- numeric() #initialize

  for (i in 1:length(gammaS)){
    simulationMxTotal[i] <- max(updateFunction (Iterations, FinalA, N, contamVec, r, gammaS[i], beta) [[2]],
                              na.rm = TRUE)
  }
  
  no.difference [k] <- all(diff(simulationMxTotal) ==0)
}

mean(no.difference) # 0.89 

```





```{r}
# how many compartments/how ridgid are the compartments?
probVec <- c(0.3,0.5,0.7)
# Environment virus decay -- how much effort is put into cleaning/new material
gamma <- 0.1

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC1_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1_1 [[1]],simulationOutputC1_1 [[2]],simulationOutputC1_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

```









