---
title: "Simulations II"
output: html_notebook
---
Different simulations:

```{r}
install.packages("ggplot2")
library("ggplot2")

```


Fixed Parameters:
```{r}
#parameters:
# Recovery rate parameter
r <- 0.8
# Environment virus decay 
gamma <- 0.1
# Environment infection parameter
alpha <- ((r*gamma)/(N+1))
# Number of iterations
Iterations <- 20
#size of population
N <- 300
#number of locations
Place <- 3
#contamination levels
contamVec<- c(5,10,15)

#fix to a medium "mixing level"
probVec <- c(0.3,0.4,0.5)

```



Condition 1: all people distributed over 3 places with no overlap:

```{r}
#vector with probabilities of having additional link to a given location
# Choose the proportion of second degree 
# some individuals contact several places; 
#probVec[1]: probability of having a second degree at location1; other indices respectivel
beta <- c(1,1,1)

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC1_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1_1 [[1]],simulationOutputC1_1 [[2]],simulationOutputC1_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

```

```{r}
beta <- c(0.5,0.5,0.5)

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutput<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma,beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutput [[1]],simulationOutput [[2]],simulationOutput [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()
```
```{r}
beta <- c(0.1,0.5,0.8)

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC2_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma, beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC2_1 [[1]],simulationOutputC2_1 [[2]],simulationOutputC2_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()
```

```{r}
probVec <- c(0.8, 0.9, 0.9)
beta <- c(0.1,0.4,0.3)

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutput<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma,beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutput [[1]],simulationOutput [[2]],simulationOutput [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()
```

```{r}
probVec <- c(1, 1, 1) #all people are at all locations
beta <- c(0.1,0.4,0.3)

FinalA <- createFinalAMat (N,Place,probVec)
simulationOutputC3_1<- updateFunction (Iterations, FinalA, N, contamVec, r, gamma,beta)

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC3_1 [[1]],simulationOutputC3_1 [[2]],simulationOutputC3_1 [[3]] ),
                  Type = rep(c("TotalSusceptible", "TotalInfected", "TotalRecovered"), each=20) )

ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()
```

Plotting the three conditions in one plot. Here only the Total Infected
```{r}

data<- data.frame(Iterations = rep(seq(1,Iterations,1),3), 
                  Vals = c(simulationOutputC1 [[2]], simulationOutputC2 [[2]], simulationOutputC3 [[2]] ),
                  Type = rep(c("Condition 1", "Condition 2", "Condition3"), each=20) )


ggplot(data=data, aes(x=Iterations, y=Vals, group=Type)) +
  geom_line(aes(linetype=Type, color = Type))+
  geom_point()

```